language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: <YOUR ENCRYPTED KEY HERE>
  app: Drops in the Bucket
  on:
    repo: <YOUR REPO INFO HERE>
services:
	mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server