language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: PzqQuJj0I7TlIE253vxy80XdIs4Vjz00+I2e/M6JtZtDnVusschuWL2s4AGZIbYJHe/cYS+vI9gk8MdkPc8f+8hh9anr2EuKqtyBMkQf99ehJxvIfStotUteGoj+4qAG1x5tSbd2Rg7DQ/lPJ4F05gDgFkM/T1nl/FRnFckjHcpyj2zObr7cUWo3fkjz3S90IQPFEpKvuXe7efecGnntWNm7GuuWjU34k0DeaYneElK+Ds0B8yZheZ5joFKEgVgBLps3pb/hWHf3RAPzQK587x7UUc2dOl0WzlDcg+CzSXKiYvkpvkXjms+0TsnsVHm9+uHsCiinp36kqcdT0yTLzlatTgmkpzc7YHhU/jFQkEbZnOthAcmQZlJok+ARe7xDC28EDbIZIpjHi4w3s3P2l4EmM0DiqXYMM/QgavaOQ1dzlh7NJhYMfGw9AIml2Wgu0ReHw8OCoj3jM3OKo0+3RzHi7zL/PLjbC9kyQCYtZUnjEdWGqj/fRu5PyQqDO3BPXijQ6Aux5S8TC69CmEN0EsU4mWcbPftQWrwXAXGKggXrwVldCV/NlECtuC8LspM1KG/Bz9TXUbiK9nYT/4Rof7eMsT6fRj1zLMFjkFjZugdaEQGkvpg8mlQqmPrGsep/yM+k0vNQS83FltNAXwK9tSWIiiNkAqr+P26kZEItosg=
  app: drops-in-the-bucket
  on:
    repo: oilylyme/drops-in-the-bucket
services: mongodb
addons:
  apt:
    sources: mongodb-3.2-precise
    packages: mongodb-org-server
